namespace LgymApi.ArchitectureTests;

internal static class ProjectReferenceGraphManifest
{
    public static readonly string[] ProjectNames =
    [
        "LgymApi.Api",
        "LgymApi.Application",
        "LgymApi.ArchitectureTests",
        "LgymApi.BackgroundWorker",
        "LgymApi.BackgroundWorker.Common",
        "LgymApi.DataSeeder",
        "LgymApi.DataSeeder.Tests",
        "LgymApi.Domain",
        "LgymApi.Identity",
        "LgymApi.Infrastructure",
        "LgymApi.IntegrationTests",
        "LgymApi.Notifications",
        "LgymApi.Platform",
        "LgymApi.Resources",
        "LgymApi.Resources.Generator",
        "LgymApi.TestUtils",
        "LgymApi.TrainingPlanning",
        "LgymApi.UnitTests"
    ];

    public static readonly string[] EdgeIdentities =
    [
        "LgymApi.Api -> LgymApi.Application",
        "LgymApi.Api -> LgymApi.BackgroundWorker",
        "LgymApi.Api -> LgymApi.Domain",
        "LgymApi.Api -> LgymApi.Identity",
        "LgymApi.Api -> LgymApi.Infrastructure",
        "LgymApi.Api -> LgymApi.Notifications",
        "LgymApi.Api -> LgymApi.Platform",
        "LgymApi.Api -> LgymApi.Resources",
        "LgymApi.Api -> LgymApi.TrainingPlanning",
        "LgymApi.Application -> LgymApi.Domain",
        "LgymApi.Application -> LgymApi.Identity",
        "LgymApi.Application -> LgymApi.Platform",
        "LgymApi.Application -> LgymApi.Resources",
        "LgymApi.Application -> LgymApi.TrainingPlanning",
        "LgymApi.ArchitectureTests -> LgymApi.Api",
        "LgymApi.ArchitectureTests -> LgymApi.Application",
        "LgymApi.ArchitectureTests -> LgymApi.BackgroundWorker.Common",
        "LgymApi.ArchitectureTests -> LgymApi.Domain",
        "LgymApi.ArchitectureTests -> LgymApi.Identity",
        "LgymApi.ArchitectureTests -> LgymApi.Infrastructure",
        "LgymApi.ArchitectureTests -> LgymApi.Notifications",
        "LgymApi.ArchitectureTests -> LgymApi.Platform",
        "LgymApi.ArchitectureTests -> LgymApi.Resources",
        "LgymApi.ArchitectureTests -> LgymApi.TrainingPlanning",
        "LgymApi.BackgroundWorker -> LgymApi.Application",
        "LgymApi.BackgroundWorker -> LgymApi.BackgroundWorker.Common",
        "LgymApi.BackgroundWorker -> LgymApi.Identity",
        "LgymApi.BackgroundWorker -> LgymApi.Infrastructure",
        "LgymApi.BackgroundWorker -> LgymApi.Notifications",
        "LgymApi.BackgroundWorker -> LgymApi.Platform",
        "LgymApi.BackgroundWorker.Common -> LgymApi.Domain",
        "LgymApi.DataSeeder -> LgymApi.Domain",
        "LgymApi.DataSeeder -> LgymApi.Identity",
        "LgymApi.DataSeeder -> LgymApi.Infrastructure",
        "LgymApi.DataSeeder.Tests -> LgymApi.DataSeeder",
        "LgymApi.DataSeeder.Tests -> LgymApi.Domain",
        "LgymApi.DataSeeder.Tests -> LgymApi.Identity",
        "LgymApi.DataSeeder.Tests -> LgymApi.Infrastructure",
        "LgymApi.Identity -> LgymApi.Domain",
        "LgymApi.Identity -> LgymApi.Platform",
        "LgymApi.Identity -> LgymApi.Resources",
        "LgymApi.Infrastructure -> LgymApi.Application",
        "LgymApi.Infrastructure -> LgymApi.BackgroundWorker.Common",
        "LgymApi.Infrastructure -> LgymApi.Domain",
        "LgymApi.Infrastructure -> LgymApi.Identity",
        "LgymApi.Infrastructure -> LgymApi.Notifications",
        "LgymApi.Infrastructure -> LgymApi.Platform",
        "LgymApi.Infrastructure -> LgymApi.TrainingPlanning",
        "LgymApi.IntegrationTests -> LgymApi.Api",
        "LgymApi.IntegrationTests -> LgymApi.Application",
        "LgymApi.IntegrationTests -> LgymApi.BackgroundWorker",
        "LgymApi.IntegrationTests -> LgymApi.BackgroundWorker.Common",
        "LgymApi.IntegrationTests -> LgymApi.Domain",
        "LgymApi.IntegrationTests -> LgymApi.Identity",
        "LgymApi.IntegrationTests -> LgymApi.Infrastructure",
        "LgymApi.IntegrationTests -> LgymApi.Notifications",
        "LgymApi.IntegrationTests -> LgymApi.Platform",
        "LgymApi.IntegrationTests -> LgymApi.Resources",
        "LgymApi.IntegrationTests -> LgymApi.TestUtils",
        "LgymApi.IntegrationTests -> LgymApi.TrainingPlanning",
        "LgymApi.Notifications -> LgymApi.BackgroundWorker.Common",
        "LgymApi.Notifications -> LgymApi.Domain",
        "LgymApi.Notifications -> LgymApi.Identity",
        "LgymApi.Notifications -> LgymApi.Platform",
        "LgymApi.Notifications -> LgymApi.Resources",
        "LgymApi.Platform -> LgymApi.Domain",
        "LgymApi.Platform -> LgymApi.Resources",
        "LgymApi.Resources -> LgymApi.Resources.Generator",
        "LgymApi.TestUtils -> LgymApi.Application",
        "LgymApi.TestUtils -> LgymApi.BackgroundWorker",
        "LgymApi.TestUtils -> LgymApi.BackgroundWorker.Common",
        "LgymApi.TestUtils -> LgymApi.Domain",
        "LgymApi.TestUtils -> LgymApi.Identity",
        "LgymApi.TestUtils -> LgymApi.Infrastructure",
        "LgymApi.TrainingPlanning -> LgymApi.Domain",
        "LgymApi.TrainingPlanning -> LgymApi.Identity",
        "LgymApi.TrainingPlanning -> LgymApi.Platform",
        "LgymApi.TrainingPlanning -> LgymApi.Resources",
        "LgymApi.UnitTests -> LgymApi.Api",
        "LgymApi.UnitTests -> LgymApi.Application",
        "LgymApi.UnitTests -> LgymApi.BackgroundWorker",
        "LgymApi.UnitTests -> LgymApi.BackgroundWorker.Common",
        "LgymApi.UnitTests -> LgymApi.Domain",
        "LgymApi.UnitTests -> LgymApi.Identity",
        "LgymApi.UnitTests -> LgymApi.Infrastructure",
        "LgymApi.UnitTests -> LgymApi.Notifications",
        "LgymApi.UnitTests -> LgymApi.Platform",
        "LgymApi.UnitTests -> LgymApi.Resources",
        "LgymApi.UnitTests -> LgymApi.TestUtils",
        "LgymApi.UnitTests -> LgymApi.TrainingPlanning"
    ];

    public static readonly string[] TopologicalOrder =
    [
        "LgymApi.Domain",
        "LgymApi.BackgroundWorker.Common",
        "LgymApi.Resources.Generator",
        "LgymApi.Resources",
        "LgymApi.Platform",
        "LgymApi.Identity",
        "LgymApi.Notifications",
        "LgymApi.TrainingPlanning",
        "LgymApi.Application",
        "LgymApi.Infrastructure",
        "LgymApi.BackgroundWorker",
        "LgymApi.Api",
        "LgymApi.ArchitectureTests",
        "LgymApi.DataSeeder",
        "LgymApi.DataSeeder.Tests",
        "LgymApi.TestUtils",
        "LgymApi.IntegrationTests",
        "LgymApi.UnitTests"
    ];

    public static readonly IReadOnlySet<string> ForbiddenEdgeIdentities = ProjectNames
        .SelectMany(source => ProjectNames
            .Where(target => !string.Equals(source, target, StringComparison.Ordinal))
            .Select(target => $"{source} -> {target}"))
        .Except(EdgeIdentities, StringComparer.Ordinal)
        .ToHashSet(StringComparer.Ordinal);
}
